services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_LOG_LEVEL: warning
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'echo "db.adminCommand("ping")" | mongosh --quiet localhost:27017 || exit 1',
        ]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 10

  ffmpeg:
    build:
      context: .
      dockerfile: ./apps/ffmpeg/Dockerfile
    container_name: ffmpeg
    ports:
      - '3334:3334'
    env_file:
      - .env.dev
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3334/health']
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s

  api:
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    container_name: api
    depends_on:
      mongo:
        condition: service_healthy
      ffmpeg:
        condition: service_healthy
    ports:
      - '3333:3333'
    env_file:
      - .env.dev
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3333/health']
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s
    entrypoint:
      [
        '/usr/local/bin/wait-for.sh',
        '-t',
        'mongo',
        'mongo:27017',
        '-t',
        'health',
        'ffmpeg',
        '--',
        'node',
        './dist/index.js',
      ]

volumes:
  mongo_data:
