services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_LOG_LEVEL: warning
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'echo "db.adminCommand("ping")" | mongosh --quiet localhost:27017 || exit 1',
        ]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 10

  api:
    image: yagomarinho/davna:latest
    container_name: api
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - '3333:3333'
    env_file:
      - ./.env
    entrypoint:
      [
        '/usr/local/bin/wait-for-mongo.sh',
        'mongo:27017',
        '--',
        'node',
        './dist/index.js',
      ]

  ffmpeg:
    image: yagomarinho/davna-ffmpeg:latest
    container_name: ffmpeg
    restart: unless-stopped
    ports:
      - '3334'
    env_file:
      - ./.env

volumes:
  mongo_data:
#
