services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_LOG_LEVEL: warning
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'echo "db.adminCommand("ping")" | mongosh --quiet localhost:27017 || exit 1',
        ]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 10

  api:
    build:
      context: ../../
      dockerfile: ./apps/api/Dockerfile
    container_name: api
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - '3333:3333'
    env_file:
      - ../../.env.dev
    entrypoint:
      [
        '/usr/local/bin/wait-for.sh',
        'mongo:27017',
        '--',
        'node',
        './dist/index.js',
      ]

volumes:
  mongo_data:
